; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
core_dir = .pio/core
default_envs =
    ; defect_detector
    development
    ; ${build.commonly_used}
extra_configs =
    targets/common.ini
    targets/quality_control.ini
    targets/unified_esp32.ini
    targets/unified_rp2040.ini
    targets/unified_samd21.ini
    targets/unified_samd51.ini
    targets/unified_stm32.ini
    targets/unified_teensy3x.ini
    targets/unified_teensy4x.ini
include_dir = src
lib_dir = src
src_dir = src
test_dir = 

[env:development]
board = adafruit_metro_m4
build_flags =
build_src_flags =
    ; Force GNU C++ 23:
    -std=gnu++23
    ; Compile hardening flags:
    -O2
    -Wall
    -Wextra
    -Wformat
    -Wformat=2
    ; -Wconversion ; Disabled due to spamming conversion issues in packages outside the scope of CRSF for Arduino.
    -Wimplicit-fallthrough
    -U_FORTIFY_SOURCE
    -D_FORTIFY_SOURCE=3
    -D_GLIBCXX_ASSERTIONS
    ; -fsrict-flex-arrays=3 ; Not available in GCC Arm Compiler v12.3.1
    -fstack-clash-protection
    -fstack-protector-strong
build_src_filter = 
    +<../examples/platformio/serial_transmitter_prototype.cpp>
    +<*/*/*.cpp>
    +<*.cpp>
build_type = debug
build_unflags =
    -c++11
    -Os
check_flags =
    --enable=all
    --disable=missingInclude
    --disable=unusedFunction
    --language=c++
    --std=c++23
check_severity = low, medium, high
check_skip_packages = yes
check_tool = cppcheck
extends = env_common_samd51
platform_packages =
    platformio/toolchain-gccarmnoneeabi @ 1.120301.0 ; PlatformIO's latest GCC Compiler version
