[platformio]
core_dir = .pio/core
workspace_dir = .pio
include_dir = src
lib_dir = src
src_dir = src
test_dir = src
default_envs = ${build.verified_targets}
extra_configs =
    src/build/targets/common.ini
    src/build/targets/quality_control.ini
    src/build/targets/unified_development.ini
