name: Submit a bug report
description: Create a bug report and help me improve CRSF for Arduino
labels: ["🐞 Bug 🐞", "Pending 📌"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug in CRSF for Arduino.
        Please fill out the form below to help me improve CRSF for Arduino.
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this bug?
      description: Please check if there is already an issue for this bug.
      options: 
        - label: I have searched the issues and there is no existing issue for this bug.
          required: true
  - type: dropdown
    id: development-environment
    attributes:
      label: What development environment are you using?
      description: Are you using the Arduino IDE or PlatformIO?
      options:
        - Arduino IDE
        - PlatformIO
    validations:
      required: true
  - type: dropdown
    id: board
    attributes:
      label: What board are you using?
      description: |
        Please select the board you are using.
        Please note that only the boards listed below are supported.
      options:
        - Adafruit Feather ESP32
        - Adafruit Feather ESP32-S2
        - Adafruit Feather ESP32-S3 (2 MB PSRAM)
        - Adafruit Feather ESP32-S3 (No PSRAM)
        - Adafruit Feather F405
        - Adafruit Feather M0 (Any variants EG Bluefruit LE, LoRa, etc)
        - Adafruit Feather M0 Express
        - Adafruit Feather M4 Express
        - Adafruit Feather M4 CAN Express
        - Adafruit Grand Central M4
        - Adafruit ItsyBitsy ESP32
        - Adafruit ItsyBitsy M0 Express
        - Adafruit ItsyBitsy M4 Express
        - Adafruit Metro ESP32-S2
        - Adafruit Metro M0 Express
        - Adafruit Metro M4 Express
        - Adafruit Metro M4 AirLift Lite
        - Adafruit QtPy ESP32 Pico
        - Adafruit QtPy ESP32-C3
        - Adafruit QtPy ESP32-S2
        - Adafruit QtPy ESP32-S3
        - Adafruit QtPy M0
        - Adafruit Trinket M0
        - Arduino MKR 1000
        - Arduino MKR FOX 1200
        - Arduino MKR GSM 1400
        - Arduino MKR NB 1500
        - Arduino MKR VIDOR 4000
        - Arduino MKR WAN 1300
        - Arduino MKR WAN 1310
        - Arduino MKR WiFi 1010
        - Arduino MKR ZERO
        - Arduino Nano 33 IoT
        - Arduino Nano RP2040 Connect
        - Arduino Zero
        - Black Pill F103C8
        - Black Pill F103C8 (128 KB Flash)
        - Black Pill F401CC
        - Black Pill F411CE
        - Blue Pill F103C6
        - Blue Pill F103C8
        - Blue Pill F103C8 (128 KB Flash)
        - Espressif ESP32-C3 DevKitC-02
        - Espressif ESP32-C3 DevKitM-1
        - Espressif ESP32-S3 DevKitC-1-N8
        - Raspberry Pi Pico RP2040
        - Seeed Studio Xiao ESP32-C3
        - Seeed Studio Xiao ESP32-S3
        - Seeed Studio XIAO SAMD21
        - SparkFun ESP32 RedBoard IoT
        - SparkFun ESP32 Thing
        - SparkFun ESP32 Thing Plus
        - SparkFun ESP32-S2 Thing Plus
        - SparkFun MicroMod F405
        - ST Black F407VE
        - ST Black F407VG
        - ST Black F407ZE
        - ST Black F407ZG
        - ST Blue F407VE Mini
        - ST Discovery F413ZH
        - ST Nucleo F401RE
        - ST Nucleo F411RE
        - ST Nucleo F429ZI
        - ST Nucleo F446RE
        - ST Nucleo F4722ZE
        - STM32F103C6
        - STM32F103C8
        - STM32F103CB
        - STM32F103R6
        - STM32F103R8
        - STM32F103RB
        - STM32F103RC
        - STM32F103RD
        - STM32F103RE
        - STM32F103RF
        - STM32F103RG
        - STM32F103T6
        - STM32F103T8
        - STM32F103TB
        - STM32F103V8
        - STM32F103VB
        - STM32F103VC
        - STM32F103VD
        - STM32F103VE
        - STM32F103VF
        - STM32F103VG
        - STM32F103ZC
        - STM32F103ZD
        - STM32F103ZE
        - STM32F103ZF
        - STM32F103ZG
        - STM32F401CB
        - STM32F401CC
        - STM32F401CD
        - STM32F401CE
        - STM32F401RB
        - STM32F401RC
        - STM32F401RD
        - STM32F401RE
        - STM32F405RG
        - STM32F407VE
        - STM32F407VG
        - STM32F410C8
        - STM32F410CB
        - STM32F410R8
        - STM32F410RB
        - STM32F411CE
        - STM32F411RC
        - STM32F411RE
        - STM32F412CE
        - STM32F412CG
        - STM32F412RE
        - STM32F412RG
        - STM32f413CG
        - STM32F413CH
        - STM32F413RG
        - STM32F413RH
        - STM32F415RG
        - STM32F417VE
        - STM32F417VG
        - STM32F423CH
        - STM32F423RH
        - STM32F446RC
        - STM32F446RE
        - Teensy 3.0
        - Teensy 3.1/3.2
        - Teensy 3.5
        - Teensy 3.6
        - Teensy 4.0
        - Teensy 4.1
    validations:
      required: true
  - type: dropdown
    id: bug-type
    attributes:
      label: What part of CRSF for Arduino is this bug related to?
      description: Please select the part of CRSF for Arduino that this bug is related to.
      options:
        - Build/Compile/Upload
        - Compatibility Table
        - RC Channels
        - Other (please specify)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current behaviour
      description: Provide a clear and concise description of the bug.
      placeholder: |
        A clear and concise description of what the bug is.
        EG: When I try to compile the code I get this error...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behaviour
      description: Provide a clear and concise description of what you expected to happen.
      placeholder: |
        A clear and concise description of what you expected to happen.
        EG: The code should compile without any errors.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: |
        Provide a clear and concise description of how to reproduce the bug.
        Please include any code that is required to reproduce the bug.
      placeholder: |
        A clear and concise description of how to reproduce the bug.
        EG: To reproduce the bug, compile the code with the following settings...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: |
        Provide any additional information that may be relevant to the bug.
        EG: I am using the following version of the Arduino IDE...

        Tip: You can paste code, logs, or config files into the text box below.
        Screenshots can also be pasted into the text box below.
    validations:
      required: false
